default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: petGolden_development

test:
  <<: *default
  database: petGolden_test


production:
  <<: *default
  database: petGolden_production
  username: petGolden
  password: <%= ENV['PETGOLDEN_DATABASE_PASSWORD'] %>
